[package]
name = "mos-hardware"
version = "0.1.0"
edition = "2021"
authors = ["Mikael Lund <lyssky@icloud.com>"]
homepage = "https://github.com/mlund/mos-hardware"
repository = "https://github.com/mlund/mos-hardware"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["commodore", "c64", "mega65", "8-bit"]
categories = ["embedded", "no-std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
lto = true
opt-level = 2
debug = 2
codegen-units = 1

[profile.release]
opt-level = 3
lto = true
debug = 2

[patch.crates-io]
ufmt = {git="https://github.com/mrk-its/ufmt", branch="ptr_width_16_fix"}
ufmt-write = {git="https://github.com/mrk-its/ufmt", branch="ptr_width_16_fix"}

[dependencies]
memoffset = {version = "0.6", features = ["unstable_const"]}
static_assertions = "1.1.0"
bitflags = "1.3.2"
volatile-register = "0.2.1"

[dev-dependencies]
ufmt-stdio = "0"
itertools = {version = "0.10.3", default-features = false}
